---
clone:
  path: k8s.io/kubernetes

build:
  image: gcr.io/google_containers/kubekins-test
  environment:
    REPO_DIR: "/drone/src/k8s.io/kubernetes"
    PATH: "/drone/bin:/drone/src/k8s.io/kubernetes/third_party/etcd:/go/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
    KUBE_RACE: "-race"
    KUBE_COVER: "n"
    KUBE_JUNIT_REPORT_DIR: "/workspace/artifacts"
    KUBE_KEEP_VERBOSE_TEST_OUTPUT: "y"
    KUBE_TIMEOUT: "-timeout 300s"
    KUBE_INTEGRATIONTEST_MAX_CONCURRENCY: "4"
    LOG_LEVEL: "4"
    KUBE_TEST_API_VERSIONS: "v1,extensions/v1beta1"
    KUBE_TEST_ETCD_PREFIXES: registry
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
  commands:
    - mkdir -p /workspace/artifacts
    - apt-get install -yqq apt-transport-https
    - apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
    - echo 'deb https://apt.dockerproject.org/repo debian-jessie main' > /etc/apt/sources.list.d/docker.list
    - apt-get update
    - apt-get install -yqq docker-engine
    - go get github.com/tools/godep
    - go get github.com/jstemmer/go-junit-report
    - ./hack/build-go.sh
    - godep go install ./...
    - ./hack/install-etcd.sh
    - ./hack/verify-all.sh -v
    #- make verify BRANCH=$$BRANCH
    - ./hack/test-go.sh -- -p=2
    - ./hack/test-cmd.sh
    - ./hack/test-integration.sh
    - ./hack/test-update-storage-objects.sh
